wandb_version: 1

activation_function:
  value: TANH
batch_size:
  value: 32
epochs:
  value: 100
initialization:
  value: XAVIER
layer_size:
  value: 64
learning_rate:
  value: 1.0e-05
num_layers:
  value: 2
optimizer:
  value: NADAM
weight_decay:
  value: 0.0005
