wandb_version: 1

activation_function:
  value: TANH
batch_size:
  value: 32
epochs:
  value: 100
initialization:
  value: XAVIER
layer_size:
  value: 32
learning_rate:
  value: 0.0001
num_layers:
  value: 1
optimizer:
  value: ADAM
weight_decay:
  value: 0.0005
