wandb_version: 1

activation_function:
  value: TANH
batch_size:
  value: 32
epochs:
  value: 40
initialization:
  value: XAVIER
layer_size:
  value: 32
learning_rate:
  value: 1.0e-05
loss_function:
  value: MSE
num_layers:
  value: 1
optimizer:
  value: ADAM
weight_decay:
  value: 0.0005
