wandb_version: 1

activation_function:
  value: RELU
batch_size:
  value: 1
epochs:
  value: 50
initialization:
  value: HE
layer_size:
  value: 64
learning_rate:
  value: 1.0e-06
num_layers:
  value: 1
optimizer:
  value: SGD
weight_decay:
  value: 0.0005
