wandb_version: 1

activation_function:
  value: RELU
batch_size:
  value: 16
epochs:
  value: 100
initialization:
  value: RANDOM
layer_size:
  value: 16
learning_rate:
  value: 1.0e-07
num_layers:
  value: 1
optimizer:
  value: SGD
weight_decay:
  value: 0
