wandb_version: 1

activation_function:
  value: RELU
batch_size:
  value: 32
epochs:
  value: 100
initialization:
  value: XAVIER
layer_size:
  value: 1
learning_rate:
  value: 1.0e-07
num_layers:
  value: 2
optimizer:
  value: MGD
weight_decay:
  value: 0.05
