wandb_version: 1

activation_function:
  value: SIGMOID
batch_size:
  value: 16
epochs:
  value: 100
initialization:
  value: RANDOM
layer_size:
  value: 32
learning_rate:
  value: 0.0001
num_layers:
  value: 1
optimizer:
  value: SGD
weight_decay:
  value: 0
