wandb_version: 1

activation_function:
  value: SIGMOID
batch_size:
  value: 16
epochs:
  value: 50
initialization:
  value: HE
layer_size:
  value: 32
learning_rate:
  value: 0.001
num_layers:
  value: 1
optimizer:
  value: NAG
weight_decay:
  value: 0
