wandb_version: 1

activation_function:
  value: TANH
batch_size:
  value: 16
epochs:
  value: 20
initialization:
  value: XAVIER
layer_size:
  value: 64
learning_rate:
  value: 1.0e-05
loss_function:
  value: CE
num_layers:
  value: 2
optimizer:
  value: ADAM
weight_decay:
  value: 0.005
