wandb_version: 1

activation_function:
  value: SIGMOID
batch_size:
  value: 32
epochs:
  value: 50
initialization:
  value: RANDOM
layer_size:
  value: 64
learning_rate:
  value: 1.0e-05
num_layers:
  value: 1
optimizer:
  value: NADAM
weight_decay:
  value: 0
