wandb_version: 1

activation_function:
  value: SIGMOID
batch_size:
  value: 16
epochs:
  value: 50
initialization:
  value: HE
layer_size:
  value: 128
learning_rate:
  value: 5.0e-06
num_layers:
  value: 1
optimizer:
  value: NADAM
weight_decay:
  value: 0
