wandb_version: 1

activation_function:
  value: TANH
batch_size:
  value: 8
epochs:
  value: 50
initialization:
  value: RANDOM
layer_size:
  value: 32
learning_rate:
  value: 0.0001
num_layers:
  value: 2
optimizer:
  value: ADAM
weight_decay:
  value: 0.05
