wandb_version: 1

activation_function:
  value: SIGMOID
batch_size:
  value: 32
epochs:
  value: 50
initialization:
  value: RANDOM
layer_size:
  value: 128
learning_rate:
  value: 0.0001
num_layers:
  value: 1
optimizer:
  value: MGD
weight_decay:
  value: 0
