wandb_version: 1

activation_function:
  value: TANH
batch_size:
  value: 16
epochs:
  value: 50
initialization:
  value: RANDOM
layer_size:
  value: 64
learning_rate:
  value: 5.0e-06
num_layers:
  value: 2
optimizer:
  value: ADAM
weight_decay:
  value: 0.0005
