wandb_version: 1

activation_function:
  value: SIGMOID
batch_size:
  value: 8
epochs:
  value: 50
initialization:
  value: HE
layer_size:
  value: 32
learning_rate:
  value: 1.0e-06
num_layers:
  value: 1
optimizer:
  value: NADAM
weight_decay:
  value: 0.05
