wandb_version: 1

activation_function:
  value: SIGMOID
batch_size:
  value: 16
epochs:
  value: 20
initialization:
  value: HE
layer_size:
  value: 128
learning_rate:
  value: 1.0e-05
num_layers:
  value: 2
optimizer:
  value: NAG
weight_decay:
  value: 0
