wandb_version: 1

activation_function:
  value: SIGMOID
batch_size:
  value: 32
epochs:
  value: 20
initialization:
  value: HE
layer_size:
  value: 128
learning_rate:
  value: 5.0e-06
num_layers:
  value: 1
optimizer:
  value: RMSPROP
weight_decay:
  value: 0.05
