wandb_version: 1

activation_function:
  value: TANH
batch_size:
  value: 32
epochs:
  value: 20
initialization:
  value: XAVIER
layer_size:
  value: 32
learning_rate:
  value: 5.0e-06
num_layers:
  value: 1
optimizer:
  value: SGD
weight_decay:
  value: 0
