wandb_version: 1

activation_function:
  value: SIGMOID
batch_size:
  value: 32
epochs:
  value: 20
initialization:
  value: RANDOM
layer_size:
  value: 128
learning_rate:
  value: 0.0001
num_layers:
  value: 2
optimizer:
  value: NADAM
weight_decay:
  value: 0.05
